#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$ROOT_DIR/terraform"
TFVARS_FILE="$TF_DIR/lab.auto.tfvars"
AUTO_APPROVE="${AUTO_APPROVE:-false}"

fail() {
  echo "Error: $*" >&2
  exit 1
}

require_command() {
  local command_name="$1"

  command -v "$command_name" >/dev/null 2>&1 || \
    fail "$command_name is not installed or not in PATH."
}

[[ -d "$TF_DIR" ]] || fail "Terraform directory not found: $TF_DIR"

[[ -f "$TFVARS_FILE" ]] || {
  echo "Terraform variable file not found: $TFVARS_FILE"
  echo "This file is generated by build_lab.sh and preserves the exact inputs"
  echo "needed to destroy the lab without detecting your public IP again."
  exit 1
}

for command_name in terraform aws; do
  require_command "$command_name"
done

echo "Verifying AWS credentials..."
AWS_ACCOUNT_ID="$(aws sts get-caller-identity \
  --query Account \
  --output text 2>/dev/null)" || \
  fail "AWS credentials are unavailable or invalid."

echo "Using AWS account: $AWS_ACCOUNT_ID"

echo
echo "Destroying Kubernetes lab resources..."
echo

terraform -chdir="$TF_DIR" init
terraform -chdir="$TF_DIR" fmt -check -recursive
terraform -chdir="$TF_DIR" validate

destroy_args=()

if [[ "$AUTO_APPROVE" == "true" ]]; then
  destroy_args+=("-auto-approve")
elif [[ "$AUTO_APPROVE" != "false" ]]; then
  fail "AUTO_APPROVE must be true or false."
fi

terraform -chdir="$TF_DIR" destroy "${destroy_args[@]}"

echo
echo "Verifying that Terraform no longer tracks any resources..."

remaining_resources="$(terraform -chdir="$TF_DIR" state list)"

if [[ -n "$remaining_resources" ]]; then
  echo "Terraform still tracks the following resources:" >&2
  echo "$remaining_resources" >&2
  fail "State and local configuration files were not removed."
fi

echo "Terraform state is empty."

echo
echo "Removing local files created by build_lab.sh..."
rm -f "$ROOT_DIR/ssh_config"
rm -f "$ROOT_DIR/lab_hosts.txt"
rm -f "$ROOT_DIR/.known_hosts"
rm -f "$TFVARS_FILE"

echo "Removing empty local Terraform state files..."
rm -f "$TF_DIR/terraform.tfstate"
rm -f "$TF_DIR/terraform.tfstate.backup"

echo
echo "Lab destroyed."